name = "seren-dev"
compatibility_date = "2026-03-12"
# workers_dev = false

[assets]
directory = "./dist/"
not_found_handling = "404-page"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GITHUB_CACHE"
